### ISSUE TITLE
Add a separate reference white for reflective displays

### ISSUE THREAD

**Issue by euan-smith** [CIELab-gamut-tools/gamut-volume-m#12]
For reflective displays the adaptive state is not the white of the display but the reflected white of a reference reflector.

Add the ability to separately specify the reference white for the gamut.

**Comment by luminextec** [comment]
For reflective display gamut volumes, the maximum L* will typically not reach L*=100 and the minimum L* will not reach L*=0. Therefore, the code should determine the maximum and minimum L* and scale the gamut volume and gamut rings plots accordingly. It would also be helpful to have the option to limit the a*rss and b*rss axes to fixed values.

**Comment by luminextec** [comment]
I noticed a couple of other features that would be good to have for the reflective display gamut volume code:
1. The hue vector arrows will sometimes lose their color and be the wrong size for the plot when the gamut rings size is small. Fix the hue arrow colors to red, green, and blue. And make the arrow size proportional to the axes size.
2. Change the default background color to white.

**Comment by euan-smith** [comment]
So to take these one-at-a-time:
**Setting reference white** this would be an enhancement to the `CIELabGamut` function.  Simplest would be to have an optional final argument of the reference white as an XYZ triplet.  The downside to this approach would be if there is any likelyhood of other options being required in future.  There are two which might be adjusted - the number of L* steps or hue steps.  So, in that case, we can add general parameters, with a few parameters available initially.  Syntax will be something like:

```
   gamut = CIELabGamut();
   gamut = CIELabGamut(filename);
   gamut = CIELabGamut(filepath);
   gamut = CIELabGamut(filepath, filter);
   gamut = CIELabGamut(RGB,XYZ,title);
% in addition to any of the above
   gamut = CIELabGamut(..., 'reference', [X, Y, Z]);
   gamut = CIELabGamut(..., 'L-steps', 100);
   gamut = CIELabGamut(..., 'h-steps', 360);
```
No options can be added which require a string argument.  Because one of the standard forms of calling the function is to have two strings as parameters, it would be impossible to tell the difference between a string option name and parameter and having a filepath and filter.

**L\* scaling** For the CIELab plot you are always free to set the axes as you see fit using the standard Matlab command. The `PlotVolume` function is not calculating any scaling at present, it is just the default Matlab axis range selection, so the standard Matlab approach should be taken (you don't set the scale when plotting anything else, you do it afterwards with a separate `axis` command).  For the `PlotRIngs` function, similarly you are free to set the axis range as you see fit.  There are features which may exceed the range you want, for example the primary vectors, however you are free to set the diameter of those already. Typing `doc PlotRings` will being up help for all of ther options.  Amongst there is `PrimaryChroma`, so to set the vector arrows to a length of c_rss of 200:
```
  PlotRings(gamut, 'PrimaryChroma', 200);
```

**Hue vector arrows** are drawn with the colour matched to the actual reported primary colour.  They have 'lost' their colour (presumably become grey) because that is what has happened to the measured primary colour.  I can add an options to make the arrow colours match the `output` (i.e. the measured CIELab colour converted back to RGB, current behaviour) or the `input` (i.e. the input RGB value).
```
  PlotRings(gamut, 'PrimaryVectorColour', 'input');
% I'll allow PrimaryVectorColor as well ;-)
```
As is indicated above the arrow length is settable using the `PrimaryChroma` option.

**Plot background colour**
This one is again standard matlab, for example see the answer to the same question [here](https://uk.mathworks.com/matlabcentral/answers/96159-how-can-i-change-the-background-color-from-gray-to-white-when-copying-a-figure-to-powerpoint).  This link suggests to use the following:
```
   set(gcf, 'color', 'w');
```

In general the library tries to follow Matlab norms rather than adding an additional means to do things which Matlab (and Octave) already does.

**Comment by luminextec** [comment]
I am worried that we are asking the CIELabGamut function to do too much. Wouldn’t it be easier to have a separate function called CIELabGamut_Refl to handle Reflective displays?

 

Regarding the hue vector arrows, it would be convenient if the arrows scaled with the axes scaling. This would help reduce the amount of manual manipulation required.

 

I recommend that you make the hue vector color based on the primary input as a default.

 

Thanks for the suggestions.

--John

**Comment by euan-smith** [comment]
To avoid code duplication (very bad for maintenance) ultimately there will be a function which can do all of it - your multiple functions then are thin layers on top of that and all you are doing is increasing the amount of code to maintain.  It is also true that the reference white can also be, in pricipal, specified within a cgats file, and the base function will need to deal with that in the long run.  So my preference is to parameterise one function.

Happy to add an option for the hue vector arrows to auto-scale.

It is dangerous in general to change the defaults - as this is public code somebody else may already have code which behaves in a particular way and changing the default may mean their code now does something different.  In this case it is probably harmless as it is a fairly minor visual change, I'll think on that one.

**Comment by euan-smith** [comment]
Created a new branch `enhancement/issue12`.
- Added and tested the reference parameter to the CIELabGamut function.
- Added the additional parameter definitions to PlotRings
Left to do:
- Implement the additional parameters in PlotRings
- Add some unit tests

**Comment by euan-smith** [comment]
OK, rest of the implementation done and tested.

merged into the main branch.
