### ISSUE TITLE
cumsum(...,'reverse') not supported using GNU Octave

### ISSUE THREAD

**Issue by h1t1h** [CIELab-gamut-tools/gamut-volume-m#14]
replacing line 74:
m = cm(cumsum(cm(:,1),'reverse')*2-cm(:,1)==1,:);

with:
m = cm(cumsum(flip(cm(:,1)))*2-cm(:,1)==1,:);

fixes the issue.

Since I hardly understand matlab or octave, this is not necessarily the most efficent way. At least the code works with GNU Octave 5.1.0 and 7.2.0.

By the way: are there other known problems running the code with Octave (aside from testing)?

**Comment by euan-smith** [comment]
Thanks for spotting that.  

I do usually test in Octave too, but that obviosly slipped through.

That line is in the inner loop - there are a couple of ways to fix it, so I'll see which is faster then push that.

It also uses the same method in the gamut intersection rings, so that needs fixing too.

**Comment by h1t1h** [comment]
I really appreciate your looking into it. And I cannot thank you enough for providing these tools.

**Comment by euan-smith** [comment]
OK, turns out that your suggestion was the fastest of the possible fixes!
I tested with the following one-liner which tests a lot of the code
```matlab
   PlotRings(IntersectGamuts(SyntheticGamut('sRGB'),SyntheticGamut('BT.2020')));
```
which produces (nearly) the same figure in both matlab and octave.

In the process found another minor bug which is now also fixed.  This is all in branch `bugfix/issue14` which will be merged shortly.

**Comment by euan-smith** [comment]
By the way thanks for going to the effort of joining github in order to raise the issue, I really appreciate it.  Always good to hear that people are using the code, makes it worthwhile - I'd love to hear what you do and how you make use of the code -  euan -dot- smith -at- 42t -dot- com

**Comment by h1t1h** [comment]
Hi Euan,

Thank you very much for the effort you put into fixing this issue!

About your question of how I am using your code: Every once in a while I am involved in quantifying the quality of computer displays. Measuring homogeneity, contrast and gamut can be achieved with little experimental effort (I am working for a non-profit organization…). In this context I am always looking for ways to present my results in a way, that even people without scientific background understand.

As I already mentioned: Working in a low budget environment explains, why I prefer Octave over Matlab…

Since your software is mentioned in the newest version of SIDs IDMS: Don’t you get more feedback?

Best regards


Holger Thiesemann

Clientqualitätssicherung und -Hardwaremanagement
_____________________________

Dataport
Fraunhoferstr. 16, 24118 Kiel
Internet: www.dataport.de<http://www.dataport.de/>
E-Mail: ***@***.******@***.***>
Telefon: 0431 - 32 95 6854




Von: Euan Smith ***@***.***
Gesendet: Dienstag, 30. August 2022 23:47
An: CIELab-gamut-tools/gamut-volume-m ***@***.***>
Cc: Thiesemann, Holger Dr. ***@***.***>; Author ***@***.***>
Betreff: [EXTERN]-Re: [CIELab-gamut-tools/gamut-volume-m] cumsum(...,'reverse') not supported using GNU Octave (Issue #14)


By the way thanks for going to the effort of joining github in order to raise the issue, I really appreciate it. Always good to hear that people are using the code, makes it worthwhile - I'd love to hear what you do and how you make use of the code - euan -dot- smith -at- 42t -dot- com
