### ISSUE TITLE
Error of CIELabGamut.m with 'filter' parameter

### ISSUE THREAD

**Issue by kenichiro-masaoka** [CIELab-gamut-tools/gamut-volume-m#17]
The following code example (Line 37 in _CIELabGamut.m_) will result in an error although it fits the 4th Syntax (_gamut = CIELabGamut(filepath,filter)_):

```
>> gamut = CIELabGamut('/path/to/folder','*.cgats');
Error using CIELabGamut (line 76)
Unmatched parameter name '/path/to/folder' must be a string scalar or character vector that can
represent a field name. 
```

**Comment by euan-smith** [comment]
@kenichiro-masaoka
This seems to be a regression.  This previously worked fine.  Resolving issue 12 or 14 caused this.
