### ISSUE TITLE
Distortion of Gamut Ring Intersection Rendering

### ISSUE THREAD

**Issue by kenichiro-masaoka** [CIELab-gamut-tools/gamut-volume-m#6]
The gamut rings of sRGB.txt have small bumps at some hue angles with the intersectionPlot true, whereas there are no bumps for the gamut rings without the intersection.

The following is a sample m-script:

```
sRGB = CIELabGamut('sRGB.txt');
lcd = CIELabGamut('lcd.txt');
figure
PlotRings(lcd,sRGB,'RingReference','intersection','intersectionPlot',true);
figure
PlotRings(sRGB)
```
![sRGB_intersection](https://user-images.githubusercontent.com/93879317/140656630-418c40be-e596-4b4c-973b-98a1eab79484.jpg)
)
![sRGB](https://user-images.githubusercontent.com/93879317/140656635-0b6b0645-907a-4fc7-9fae-d53e86b02280.jpg)
_

**Comment by euan-smith** [comment]
Confirmed this as a bug - thanks for spotting and reporting it!  I will have a look and see what I can find, it is most likely a bug with the intersection rather than with the intersection ring plotting.
